---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: tools
  labels:
    app: mongo
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
  selector:
    name: mongo
