---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: tools
spec:
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      namespace: tools
      annotations:
        volume.beta.kubernetes.io/storage-class: "aws-ebs"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
